# Introduction to NumPy Arrays

NumPy is a powerful Python library used for numerical computing. At the heart of NumPy is the **array** object, which is like a more efficient and flexible version of Python lists for handling large amounts of data.

NumPy arrays can be:
- **1D (one-dimensional)**: a simple list of numbers,
- **2D (two-dimensional)**: like a table or matrix,
- **3D (three-dimensional)**: a collection of 2D arrays stacked together.

NumPy also provides many useful functions to create arrays filled with specific values (like all ones or zeros), generate random numbers, and create arrays with evenly spaced values. Arrays also have attributes to get information about their shape, size, number of dimensions, and data type.


In [12]:
import numpy as np

In [13]:
# Create a 1D array of integers
one_d_array = np.array([10, 20, 30, 40, 50])
print("1D Array:", one_d_array)

# Create a 2D array (2 rows, 5 columns)
two_d_array = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
print("2D Array:\n", two_d_array)

# Create a 3D array (3 layers, each with 1 row and 5 columns)
three_d_array = np.array([
    [[1, 2, 3, 4, 5]],
    [[6, 7, 8, 9, 10]],
    [[11, 12, 13, 14, 15]]
])
print("3D Array:\n", three_d_array)

1D Array: [10 20 30 40 50]
2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D Array:
 [[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[11 12 13 14 15]]]


In [14]:
# Create arrays filled with ones and zeros
ones_array = np.ones(5)      # 1D array of five ones
zeros_array = np.zeros(5)    # 1D array of five zeros
print("Ones Array:", ones_array)
print("Zeros Array:", zeros_array)

Ones Array: [1. 1. 1. 1. 1.]
Zeros Array: [0. 0. 0. 0. 0.]


In [15]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# Generate random integers between 0 and 9, size 5
random_ints = np.random.randint(0, 10, size=5)
print("Random Integers:", random_ints)

Random Integers: [1 9 7 1 3]


In [17]:
# Create a 3x5 array filled with 9s
filled_array = np.full((3, 5), 9)
print("Filled Array with 9s:\n", filled_array)

Filled Array with 9s:
 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [18]:
# Generate a 2x5 array of random floats between 0 and 1
random_floats = np.random.rand(2, 5)
print("Random Floats:\n", random_floats)

Random Floats:
 [[0.78818928 0.63869014 0.62003989 0.76236067 0.72119549]
 [0.49469702 0.8033946  0.12621039 0.02160317 0.49080314]]


In [19]:
# Generate a 2x5 array with normal distribution (mean=0, std=2)
normal_dist_array = np.random.normal(0, 2, (2, 5))
print("Normal Distribution Array:\n", normal_dist_array)

Normal Distribution Array:
 [[-2.02781565 -2.06253449  2.24556142 -1.91633332  3.36088535]
 [-1.39674171 -0.72943308 -2.31477529 -4.3797453  -2.40145901]]


In [20]:
# Create arrays with specific ranges
range_array = np.arange(0, 15, 3)      # Values from 0 to 15 stepping by 3
linspace_array = np.linspace(0, 15, 3) # 3 evenly spaced values between 0 and 15
print("Range Array:", range_array)
print("Linspace Array:", linspace_array)

Range Array: [ 0  3  6  9 12]
Linspace Array: [ 0.   7.5 15. ]


In [21]:
# Example array for attributes demonstration
example_array = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

# Display array attributes
array_shape = example_array.shape      # Shape of the array (rows, columns)
array_size = example_array.size        # Total number of elements
array_dimensions = example_array.ndim  # Number of dimensions
array_dtype = example_array.dtype      # Data type of elements

print("Array Shape:", array_shape)
print("Array Size:", array_size)
print("Array Dimensions:", array_dimensions)
print("Array Data Type:", array_dtype)

Array Shape: (2, 5)
Array Size: 10
Array Dimensions: 2
Array Data Type: int32


In [22]:
# Convert array elements to floats
float_array = example_array.astype(float)
float_dtype = float_array.dtype
print("Float Array:\n", float_array)
print("Float Array Data Type:", float_dtype)

Float Array:
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
Float Array Data Type: float64


# Real-World Analogy: Organizing Data Like Boxes

Think of NumPy arrays as boxes for storing items:
- A **1D array** is like a single row of boxes lined up in a row.
- A **2D array** is like multiple rows of boxes stacked to form shelves.
- A **3D array** is like several shelves stacked on top of each other to form a cabinet.

Using NumPy functions is like deciding whether to fill boxes with all apples, all oranges, or a mix of random fruits, and knowing exactly how many boxes you have and what types of fruits are inside.

This organized structure helps computers process data quickly and efficiently.
