# Numpy Indexing, Slicing and Fancy Indexing

NumPy arrays allow you to access and manipulate data efficiently using:

- **Indexing:** Selecting individual elements by their position.
- **Slicing:** Extracting a range or subset of elements using start, stop, and step.
- **Fancy Indexing:** Using arrays or lists of indices to select multiple elements at once.

These techniques help work with large datasets by accessing only the parts you need, or rearranging data quickly.


In [14]:
import numpy as np

In [15]:
# Create a sample array
array = np.array([10, 20, 30, 40, 50])

In [16]:
# Indexing - access single elements
print("Element at index 0:", array[0])
print("Element at index 3:", array[3])

Element at index 0: 10
Element at index 3: 40


In [17]:
# Fancy Indexing - select multiple specific elements
indices = [0, 4, 2]
print("Elements at indices [0, 4, 2]:", array[indices])

Elements at indices [0, 4, 2]: [10 50 30]


In [18]:
# Slicing - select a range of elements
print("Elements from index 2 to 4:", array[2:5])
print("First three elements:", array[:3])
print("Array in reverse order:", array[::-1])

Elements from index 2 to 4: [30 40 50]
First three elements: [10 20 30]
Array in reverse order: [50 40 30 20 10]


In [19]:
# Multi-dimensional array example
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Entire first row:", matrix[0])
print("Element at row 1, column 2:", matrix[1, 2])

# Slicing rows and columns
print("All rows, first two columns:\n", matrix[:, :2])
print("Last two rows, all columns:\n", matrix[1:, :])

# Boolean Indexing (subsetting)
print("Elements greater than 5:", matrix[matrix > 5])

Entire first row: [1 2 3]
Element at row 1, column 2: 6
All rows, first two columns:
 [[1 2]
 [4 5]
 [7 8]]
Last two rows, all columns:
 [[4 5 6]
 [7 8 9]]
Elements greater than 5: [6 7 8 9]


# Real-World Analogy: Selecting Books from a Bookshelf

- **Indexing** is like picking a single book by its exact position on the shelf.
- **Slicing** is like taking a whole section of books from the shelf.
- **Fancy Indexing** is like grabbing specific books scattered across the shelf using a list of positions.
- **Boolean indexing** is like choosing all books that meet a certain condition, such as all books by a particular author.

These techniques make it easier to organize and retrieve data quickly.
