# Numpy Data Manipulation

Data manipulation in NumPy involves changing the structure or content of arrays without losing the original data. This includes reshaping arrays to new dimensions, combining multiple arrays into one, selecting or extracting specific elements, and filtering arrays based on conditions.

Common techniques include:
- **Reshaping:** Changing the shape of an array (e.g., from 2D to 1D).
- **Combining:** Joining arrays horizontally or vertically.
- **Indexing and Fancy Indexing:** Accessing elements by position or using arrays of indices.
- **Slicing:** Extracting parts of an array.
- **Subsetting:** Filtering elements that satisfy a condition.


In [ ]:
import numpy as np

In [ ]:
# 1- Reshaping arrays

original_array = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

# Flatten the array to 1D
flattened = original_array.flatten()
print("Flattened:", flattened)

# Reshape the array to 5 rows and 2 columns (does not modify original)
reshaped = original_array.reshape(5, 2)
print("Reshaped:\n", reshaped)

# Resize the original array to 5 rows and 2 columns (modifies in place)
original_array.resize((5, 2))
print("Resized:\n", original_array)

# Transpose swaps rows and columns
transposed = original_array.T
print("Transposed:\n", transposed)

Flattened: [ 1  2  3  4  5  6  7  8  9 10]
Reshaped:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Resized:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Transposed:
 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [ ]:
# 2- Combining arrays

array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

# Horizontal stack (combine as columns)
horiz_combined = np.hstack((array_a, array_b))
print("Horizontal Stack:", horiz_combined)

# Vertical stack (combine as rows)
vert_combined = np.vstack((array_a, array_b))
print("Vertical Stack:\n", vert_combined)

# Generic concatenate (default along axis 0 for 1D arrays)
concatenated = np.concatenate((array_a, array_b))
print("Concatenated:", concatenated)

# Stack adds a new axis (creates a 2D array)
stacked = np.stack((array_a, array_b))
print("Stacked:\n", stacked)


Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Concatenated: [1 2 3 4 5 6]
Stacked:
 [[1 2 3]
 [4 5 6]]


In [ ]:
# 3- Indexing and Fancy Indexing

indexed_array = original_array.T
print("Indexed Array (Transposed):\n", indexed_array)

# Access first row
first_row = indexed_array[0]
print("First row:", first_row)

# Access second element of first row
second_element = indexed_array[0][1]
print("Second element of first row:", second_element)

# Fancy indexing: select elements at indices 0, 4, and 2
sample_array = np.array([1, 2, 3, 4, 5])
selected_indices = [0, 4, 2]
fancy_indexed = sample_array[selected_indices]
print("Fancy indexed elements:", fancy_indexed)

Indexed Array (Transposed):
 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
First row: [1 3 5 7 9]
Second element of first row: 3
Fancy indexed elements: [1 5 3]


In [ ]:
# 4- Slicing arrays

slice_1 = sample_array[2:5]
print("Slice from index 2 to 4:", slice_1)

slice_2 = sample_array[:3]
print("First 3 elements:", slice_2)

reverse_slice = sample_array[::-1]
print("Reversed array:", reverse_slice)

column_3 = indexed_array[:, 2]
print("Third column of indexed array:", column_3)

rows_and_columns = indexed_array[0:, :3]
print("All rows, first 3 columns:\n", rows_and_columns)

Slice from index 2 to 4: [3 4 5]
First 3 elements: [1 2 3]
Reversed array: [5 4 3 2 1]
Third column of indexed array: [5 6]
All rows, first 3 columns:
 [[1 3 5]
 [2 4 6]]


In [ ]:
# 5- Subsetting with conditions

subset_1 = indexed_array[indexed_array > 2]
print("Elements greater than 2:", subset_1)

subset_2 = indexed_array[(indexed_array > 1) & (indexed_array < 4)]
print("Elements >1 and <4:", subset_2)

subset_3 = indexed_array[indexed_array != 5]
print("Elements not equal to 5:", subset_3)

conditional_array = np.where(indexed_array < 3, indexed_array, -1)
print("Conditional replace (<3 keep, else -1):\n", conditional_array)

Elements greater than 2: [ 3  5  7  9  4  6  8 10]
Elements >1 and <4: [3 2]
Elements not equal to 5: [ 1  3  7  9  2  4  6  8 10]
Conditional replace (<3 keep, else -1):
 [[ 1 -1 -1 -1 -1]
 [ 2 -1 -1 -1 -1]]


# Real-World Analogy: Sorting and Filtering Your Music Playlist

- **Reshaping** is like changing the layout of your music playlist — from a simple list of songs to grouping them by albums or artists.
- **Combining** playlists means merging different collections of songs into one.
- **Indexing** is like choosing a specific song by its position in the playlist.
- **Slicing** is selecting a part of the playlist, such as songs 5 to 10.
- **Subsetting** is filtering songs by criteria, like only songs longer than 3 minutes or those with a certain genre.

These tools help organize large datasets (or playlists!) so you can find or analyze exactly what you need quickly.
