# NumPy Performance Techniques and Broadcasting

NumPy is designed for fast and efficient numerical computing. Two key features that help boost performance are:

- **Vectorization:** Performing operations on entire arrays at once, instead of looping through elements one by one. This leverages optimized C code underneath.
  
- **Broadcasting:** A powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes by "stretching" smaller arrays to match larger ones without making copies of data.

Using these techniques reduces the need for explicit loops, resulting in cleaner and faster code.


In [1]:
import numpy as np

In [2]:
# Vectorized operation example: adding two arrays element-wise
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

result = arr1 + arr2
print("Element-wise addition:", result)

Element-wise addition: [11 22 33 44]


In [3]:
# Without vectorization, you'd need loops like this (inefficient):
# for i in range(len(arr1)):
#     result[i] = arr1[i] + arr2[i]

In [4]:
# Broadcasting example
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

# 'a' shape: (3,)
# 'b' shape: (3,1)

# When adding, 'a' is broadcasted to shape (3,3) to match 'b'
broadcast_result = b + a
print("Broadcasted addition result:\n", broadcast_result)

Broadcasted addition result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


In [5]:
# Another example: multiply a 2D array by a 1D array along columns
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
scalars = np.array([10, 20, 30])

multiplied = matrix * scalars  # scalars broadcasted to each row
print("Broadcasted multiplication:\n", multiplied)

Broadcasted multiplication:
 [[ 10  40  90]
 [ 40 100 180]]


# Real-World Analogy: Applying Discounts in a Store

Imagine you have a list of product prices and a list of discount percentages for each category.

- **Vectorization** is like applying the discount to every price at once instead of calculating one by one.
- **Broadcasting** is like applying the same discount list to multiple stores with different prices — the discounts "stretch" to fit the prices automatically.

This approach saves time and effort when dealing with many products or stores.
